version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_container
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: 'study_time_tracker'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - dbdata:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d  # マイグレーションファイルのマウント
    networks:
      - app-network
    ports:
      - "3307:3306"

  node:
    build:
      context: .
      dockerfile: NodeDockerfile
    container_name: node_container
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: npm start
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
