CREATE Table Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255), NOT NULL,
    main_goal VARCHAR(255), NOT NULL
);